
import {v4 as uuid} from "uuid"
export default [
    // "html","css","js","react","web","ts","router","redux","just"
    {
     _id:uuid(),
     hoverContent:"",
     type:"macro",
     link:"https://mytube-webapp.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/my-tube",
     head:"MYTube",
     sub:"this is the fully functional fullstack video library app.",
     desc:"",
     tag:"new",
     detail:["html","css","js","react","router",],
     logoImg:`${window.location.origin}/assets/macro1-logo.png`,
     img:`${window.location.origin}/assets/macro1.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"macro",
     link:"https://home-interior-app.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/home-interior",
     head:"interior",
     sub:"this is the fully functional fullstack ecomerce app.",
     desc:"",
     tag:"new",
     detail:["html","css","js","react","router","redux"],
     logoImg:`${window.location.origin}/assets/macro2-logo.png`,
     img:`${window.location.origin}/assets/macro2.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"macro",
     link:"https://bui-site.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/bui",
     head:"BUI",
     sub:"this is the fully functional CSS library app.",
     desc:"",
     tag:"new",
     detail:["html","css","js","react","redux","router"],
     logoImg:`${window.location.origin}/assets/macro3-logo.png`,
     img:`${window.location.origin}/assets/macro3.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"mini",
     link:"https://promodoro-web-app.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/promodoro",
     head:"Promodoro",
     sub:"this is the fully functional Promodoro app.",
     desc:"",
     tag:"new",
     detail:["html","css","ts","router"],
     logoImg:`${window.location.origin}/assets/mini1-logo.png`,
     img:`${window.location.origin}/assets/mini1.png`
    },
    {
     _id:uuid(),
     hoverContent:"My tab",
     type:"mini",
     link:"https://my-tab.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/my-tab",
     head:"My tab",
     sub:"this is the fully functional browser new tab page.",
     desc:"",
     tag:"new",
     detail:["html","css","react","redux"],
    //  logoImg:`${window.location.origin}/assets/mini1-logo.png`,
     img:`${window.location.origin}/assets/mini2.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://neog-mark14.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/Mark-14",
     head:"profit-or-loss",
     sub:"A website which helps user how much profit or loss he/she is making in percentage & absolute value.",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro1-logo.png`,
     img:`${window.location.origin}/assets/micro1.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://mark-13-faisal.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/Mark-13",
     head:"palindrome-birthdays",
     sub:"App which checks whether your birthday is a palindrome birthday or not.",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro2-logo.png`,
     img:`${window.location.origin}/assets/micro2.png`
    },
    
    {
     _id:uuid(),
     hoverContent:"Fun with Triangle",
     type:"micro",
     link:"https://mark-12-faisal.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/mark-12",
     head:"fun with triangle",
     sub:"A website which helps you to learn about triangles",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
    //  logoImg:`${window.location.origin}/assets/micro2-logo.png`,
     img:`${window.location.origin}/assets/micro3.png`
    },
    
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://luckybirthday-by-faisal.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/mark-11",
     head:"is-your-birthday-lucky",
     sub:"A website which can help you to check whether your birthday is lucky or not.",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro4-logo.png`,
     img:`${window.location.origin}/assets/micro4.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://mark10-faisal.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/neog-ex-10",
     head:"cash-register-manager",
     sub:"A cash register manager which helps the user by telling how can he/she return the change to the customer with minimum number of notes.",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro5-logo.png`,
     img:`${window.location.origin}/assets/micro5.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://oied7.csb.app/",
     gitLink:"https://oied7.csb.app/",
     head:"🏝️🌄 PLaces in India",
     sub:"I love travelling, so this are he place I like the most in India. You can check them by clicking the button bellow.",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro6-logo.png`,
     img:`${window.location.origin}/assets/micro6.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://xqvwi.csb.app/",
     gitLink:"https://xqvwi.csb.app/",
     head:"foodemoji😋",
     sub:"I struggle with understanding food names of the food mojis. Do you too? If yes, then see this library of food emojis with meaning",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro7-logo.png`,
     img:`${window.location.origin}/assets/micro7.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://mark-7-faisal.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/Fun-transulation-part-2",
     head:"Yoda Speak",
     sub:"Convert from English to Yoda speak. Yoda often orders sentences as Object-Subject-Verb, split verbs, switches entire phrases and sometimes uses sentences that are different from his normal syntax!",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro8-logo.png`,
     img:`${window.location.origin}/assets/micro8.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
     link:"https://miniontalk-faisal.netlify.app/",
     gitLink:"https://github.com/faisal-kursheedali/minion-talk",
     head:"Minion Speak",
     sub:"Are you a fan of minions? Did you know that the gibberish they say is an actual language. Use the translator to convert your text from English to Minion speak or Banana language.",
     desc:"",
    //  tag:"new",
     detail:["html","css","js"],
     logoImg:`${window.location.origin}/assets/micro9-logo.png`,
     img:`${window.location.origin}/assets/micro9.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
    //  link:"",
     gitLink:"https://replit.com/@5sal2003/Are-u-Avengers-Fan?embed=1&output=1#index.js",
     head:"are you a Avengers fan?",
     sub:"Do you know marvel cinematic universe? Let's play a quiz and see.",
     desc:"",
    //  tag:"new",
     detail:["js"],
     logoImg:`${window.location.origin}/assets/micro-cli.png`,
     img:`${window.location.origin}/assets/micro-cli.png`
    },
    {
     _id:uuid(),
     hoverContent:"",
     type:"micro",
    //  link:"",
     gitLink:"https://replit.com/@5sal2003/final-pog?embed=1&output=1#index.js",
     head:"how well do you know me?",
     sub:"A CLI app built with nodeJS. Let's see how much you know about me.",
     desc:"",
    //  tag:"new",
     detail:["js"],
     logoImg:`${window.location.origin}/assets/micro-cli.png`,
     img:`${window.location.origin}/assets/micro-cli.png`
    },
    
    
]